version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      non-major-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    groups:
      non-major-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    schedule:
      interval: weekly
