openapi: 3.1.0
info:
  title: OpenAPI v3.1.0 example with array type
  version: 1.0.0
paths:
  /array-type:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type:
                      - string
                      - null
                  no:
                    type: 
                      - number
                      - null
