openapi: 3.0.3
info:
  title: Recursive API
  version: 1.0.0
paths:
  /api/some-folder:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FolderDto'
components:
  schemas:
    FolderDto:
      type: object
      properties:
        name:
          type: string
        files:
          type: array
          items:
            type: string
        folders:
          type: array
          items:
            $ref: '#/components/schemas/FolderDto'
