name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Build, compile, and upload to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          check-latest: true

      - name: Install dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
